# Generated by Django 3.2 on 2022-01-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product_code', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('stock', models.BigIntegerField()),
                ('price', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('qrcode', models.ImageField(upload_to='')),
            ],
        ),
    ]
