# Generated by Django 3.2 on 2022-01-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0002_alter_sparepart_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='date_added',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='update_date',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
