# Generated by Django 3.2 on 2022-01-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0003_auto_20220131_0656'),
    ]

    operations = [
    ]
