# Generated by Django 3.2 on 2022-02-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0009_auto_20220202_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
