# Generated by Django 3.2 on 2022-02-02 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sparepart', '0010_alter_category_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='person_responsible',
            field=models.ForeignKey(default='Juan_as_superUser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='person_responsible',
            field=models.ForeignKey(default='Juan_as_superUser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='person_responsible',
            field=models.ForeignKey(default='Juan_as_superUser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
