# Generated by Django 3.2 on 2022-02-02 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sparepart', '0013_alter_sparepart_person_responsible_for_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='person_responsible_for_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_who_update', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
