# Generated by Django 3.2 on 2022-02-03 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0017_enhanceinoutstock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalSparePart',
        ),
    ]
