# Generated by Django 3.2 on 2022-02-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0019_historicalsparepart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enhanceinoutstock',
            name='stockin',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='enhanceinoutstock',
            name='stockout',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='first_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='stockin',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='stockout',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='HistoricalSparePart',
        ),
    ]
