# Generated by Django 3.2 on 2022-02-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0020_auto_20220203_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='enhanceinoutstock',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
