# Generated by Django 3.2 on 2022-02-04 06:49

from django.db import migrations, models
import warehouse.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0021_enhanceinoutstock_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='image',
            field=models.ImageField(storage=warehouse.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, storage=warehouse.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
    ]
