# Generated by Django 3.2 on 2022-02-04 08:01

from django.db import migrations, models
import warehouse.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0022_auto_20220204_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, storage=warehouse.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
