# Generated by Django 3.2 on 2022-02-04 09:26

from django.db import migrations, models
import warehouse.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0023_alter_sparepart_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='qrcode_s3',
            field=models.ImageField(blank=True, null=True, storage=warehouse.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
