# Generated by Django 3.2 on 2022-02-06 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sparepart', '0024_auto_20220204_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('discount', models.PositiveIntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('internal_note', models.CharField(blank=True, max_length=255, null=True)),
                ('external_note', models.CharField(blank=True, max_length=255, null=True)),
                ('parts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sparepart.sparepart')),
                ('person_responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_order', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField()),
                ('discount', models.PositiveIntegerField(default=0)),
                ('total_amount', models.PositiveBigIntegerField(default=0)),
                ('person_responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
