# Generated by Django 3.2 on 2022-02-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0026_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='request_order',
            field=models.BooleanField(default=False),
        ),
    ]
