# Generated by Django 3.2 on 2022-02-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0028_order_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
