# Generated by Django 3.2 on 2022-02-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0029_order_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='receipt',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
