# Generated by Django 3.2 on 2022-02-07 01:53

from django.db import migrations, models
import warehouse.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0031_auto_20220206_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='nama_penerima',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='no_hp',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_proof',
            field=models.ImageField(blank=True, null=True, storage=warehouse.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
        migrations.AddField(
            model_name='order',
            name='retur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='retur_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
