# Generated by Django 3.2 on 2022-02-07 04:23

from django.db import migrations, models
import warehouse.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0032_auto_20220207_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, storage=warehouse.storage_backends.PublicMediaStorage(), upload_to='')),
            ],
        ),
    ]
