# Generated by Django 3.2 on 2022-02-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0033_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='promo_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='price',
            field=models.PositiveBigIntegerField(),
        ),
    ]
