# Generated by Django 3.2 on 2022-02-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0034_auto_20220215_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
