# Generated by Django 3.2 on 2022-02-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0036_alter_sparepart_promo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid_proof',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
