# Generated by Django 3.2 on 2022-02-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0037_alter_order_paid_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
