# Generated by Django 3.2 on 2022-02-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0038_alter_logo_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelanggan', models.CharField(max_length=255)),
                ('catatan', models.CharField(blank=True, max_length=255, null=True)),
                ('alamat', models.CharField(blank=True, max_length=255, null=True)),
                ('no_hp', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
