# Generated by Django 3.2 on 2022-02-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0041_alter_customer_no_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
