# Generated by Django 3.2 on 2022-03-10 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0046_auto_20220303_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='nama_penerima',
        ),
        migrations.RemoveField(
            model_name='order',
            name='no_hp',
        ),
        migrations.CreateModel(
            name='DownPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.ImageField(upload_to='')),
                ('nilai', models.PositiveBigIntegerField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sparepart.customer')),
            ],
        ),
    ]
