# Generated by Django 3.2 on 2022-03-12 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0047_auto_20220310_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downpayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sparepart.order'),
        ),
    ]
