# Generated by Django 3.2 on 2022-03-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0048_alter_downpayment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='downpayment',
            name='delete_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
