# Generated by Django 3.2 on 2022-03-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0049_downpayment_delete_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='retur_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
