# Generated by Django 3.2 on 2022-03-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0050_auto_20220313_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(default='2022-03-15 17:45:16')),
                ('promotion', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
