# Generated by Django 3.2 on 2022-03-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0051_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='preorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='preorder_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='created_datetime',
            field=models.DateTimeField(default='2022-03-16 17:06:09'),
        ),
    ]
