# Generated by Django 3.2 on 2022-03-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0052_auto_20220316_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='created_datetime',
            field=models.DateTimeField(default='2022-03-17 11:41:32'),
        ),
    ]
